---
collapsible_nav: true
default_owner_slack: "#observability-platform"
enable_search: true
footer_links:
  Slack: https://moj.enterprise.slack.com/archives/C05QXHR697S
  Status: https://status.observability-platform.service.justice.gov.uk
full_service_name: Observability Platform User Guide
github_branch: main
github_repo: ministryofjustice/observability-platform-user-guide
header_links:
  Slack: https://moj.enterprise.slack.com/archives/C05QXHR697S
  Status: https://status.observability-platform.service.justice.gov.uk
host: https://user-guide.observability-platform.service.justice.gov.uk
max_toc_heading_level: 3
owner_slack_workspace: mojdt
phase: DISCOVERY
prevent_indexing: true
service_link: /
service_name: Observability Platform User Guide
show_contribution_banner: true
show_expiry: true
show_govuk_logo: false
show_review_banner: true
